AWSTemplateFormatVersion: 2010-09-09
Description: codedeploy backend-stack using blue/green deployment

##
## parameters: can be referenced within 'Resources'
##
Parameters:
    Vpc:
        Type: AWS::EC2::VPC::Id
        Description: vpc id

    ElbSubnets:
        Type: List<AWS::EC2::Subnet::Id>
        Description: comma-delimited list of ECS subnets

    
    HostPort:
        Type: Number
        Description: host port
        Default: 80

    ContainerPort:
        Type: Number
        Description: container port
        Default: 443
   
    TagName:
        Type: String
        Description: tag name for blue-green deployed resource
        Default: ecs-backend

    ElbProtocol:
        Type: String
        Description: >
            protocol for connections from clients to the load balancer. For
            Application Load Balancers, the supported protocols are HTTP and
            HTTPS. For Network Load Balancers, the supported protocols are TCP,
            TLS, UDP, and TCP_UDP
        Default: TCP
        AllowedValues:
          - HTTP
          - HTTPS
          - TCP
          - TLS

 
Resources:
    
    ElbTargetGroupBlue:
        Type: AWS::ElasticLoadBalancingV2::TargetGroup
        Properties:
            
#### end: Nlb ####
            Port: !Ref ContainerPort
            Protocol: !Ref ElbProtocol
            Tags:
              - Key: Group
                Value: !Ref TagName
            TargetType: ip
            VpcId: !Ref Vpc

    ElbTargetGroupGreen:
        Type: AWS::ElasticLoadBalancingV2::TargetGroup
        Properties:
            
            Port: !Ref ContainerPort
            Protocol: !Ref ElbProtocol
            Tags:
              - Key: Group
                Value: !Ref TagName
            TargetType: ip
            VpcId: !Ref Vpc

    Elb:
        Type: AWS::ElasticLoadBalancingV2::LoadBalancer
        Properties:
            Type: network
            Name: ElbBlueGreen
            IpAddressType: ipv4
            Scheme: internet-facing
#### start: Nlb ####
            
#### end: Nlb ####
            Subnets: !Ref ElbSubnets
            Tags:
              - Key: Group
                Value: !Ref TagName

    ElbListenerProdTraffic:
        Type: AWS::ElasticLoadBalancingV2::Listener
        Properties:
            DefaultActions:
              - Type: forward
                ForwardConfig:
                    TargetGroups:
                      - TargetGroupArn: !Ref ElbTargetGroupBlue
            LoadBalancerArn: !Ref Elb

            
            Port: !Ref HostPort
            Protocol: !Ref ElbProtocol

   

     
